### ISSUE TITLE
Récupération bordereau

### ISSUE THREAD

**Issue by mannouman** [bybrunobarros/node-envoimoinscher#1]
Salut, 

Bien que pas mise à jour depuis un moment, ton client pour envoimoinscher fonctionne à la perfection !

Juste une question  par rapport aux fonctions proposées : dans ta doc tu ne mentionnes pas la possibilité de récupérer les bordereaux pdf via le service  api/v1/order_status/:id//informations d'envoimoinscher.

Je vois par contre dans ton code (index.js) orderStatus: setupRequest("/order_status/{id}/informations")

Est-ce que c'est juste un oubli dans la doc ou est-ce que tu n'as pas implémenté cette fonction ? 
Si elle est dispo, peux-tu me dire comment l'appeler stp ?

Merci !

**Comment by mannouman** [comment]
Hum... sorry pour le dérangement et la fake issue , en y regardant d'un peu plus près j'ai trouvé comment appeler le service via ton client...

En tout cas, ca m'aura permis de te remercier pour ce client qui fonctionne très bien !!

Bonne soirée !

**Comment by bybrunobarros** [comment]
Salut et merci pour ce retour.

En effet, je ne maintiens pas ce projet et je n'aurais peut-être pas du le publier. En tout cas, je suis ravis de savoir qu'il tourne encore et que ça serve à quelqu'un d'autre que moi.

Je ne peux pas répondre à ta question, je ne m'en souviens plus :)
